### ISSUE TITLE
HTTP2 Support

### ISSUE THREAD

**Issue by Scarysize** [txchen/light-server#15]
Hey, have you thought about adding http2 support? Would be nice to play around with. Just asking for an opinion on that.

Feel free to close this.

**Comment by txchen** [comment]
@Scarysize I am now using connect to server http, if connect can support http2, I can definitely look into it to see how to enable it in light-server. Otherwise, it's not in my plan currently.

BTW, just curious, could you please tell me why do you think http2 in dev mode is important to you?

**Comment by Scarysize** [comment]
I think it would be nice to simulate a http2 environment to play around with. Testing how a unbundled app would behave, server-push etc. All this without setting up a "real" http2 server. 

As far as I can see it `connect` is just a listener which will be passed into a node http server. I guess you could just switch the http server for a http2 server and attach the same listener.

Here is a static file server example from the node-htttp2 module:
https://github.com/molnarg/node-http2/blob/master/example/server.js

**Comment by txchen** [comment]
Thanks! I will take a look.

**Comment by txchen** [comment]
Sorry I forgot this issue until someone sent me a PR today. 
http2 mode is implemented in https://github.com/txchen/light-server/commit/ba37170aa5a41f878fcaa0a5c8d56effa61af005

I end up using `spdy` as it can support connect/express very well.

**Comment by txchen** [comment]
published 1.1.9. Close this and thanks a lot for the proposal!

**Comment by Scarysize** [comment]
@txchen Nice, I totally forgot about this issue, too. Thanks for the implementation!
