### ISSUE TITLE
Add example

### ISSUE THREAD

**Issue by Scarysize** [txchen/light-server#16]
Hey,
would you be interested in adding a example to this repo? If so, I would open up a PR.
I have a simple example stack in mind:
- Jade Templates (now called `pug`)
- Stylus CSS
- ES5 JavaScript, bundled with `browserify` and transpiled with `babel`
- Some image assets

**Comment by txchen** [comment]
@Scarysize thanks for the idea! Please help to open up a PR since I don't have an example as comprehensive as yours :)

**Comment by Scarysize** [comment]
Basically I would add my boilerplate project as an example:

https://github.com/Scarysize/pug-stylus-es5-boilerplate

**Comment by txchen** [comment]
Great, just FYI, light-server now support config file. 
I noticed that your npm script is long because it is doing a lot of things, do you think it would be better to use config file instead?

**Comment by Scarysize** [comment]
Oh I didn´t know that. Yes I would definitly use a config file instead. I will update my project, then submit a PR

**Comment by Scarysize** [comment]
See #17
