### ISSUE TITLE
Feat: 'no-reload' option

### ISSUE THREAD

**Issue by Scarysize** [txchen/light-server#18]
Hey,

I thought it would be helpful to have an option for watch tasks to not trigger a browser reload after running the configured build task. I wanted the `reload` action to still be the default, so I have to explicitly tell the watcher to not trigger the reload. 
I did this by adding a `no-reload` option for watch tasks. Take a look here at my fork:

https://github.com/Scarysize/light-server/pull/1

What do you think? Worth merging?

**Comment by txchen** [comment]
@Scarysize thanks for the idea, really appreciate it! Please send a PR.

**Comment by Scarysize** [comment]
If fear adding to much options to this, ruining the whole "light" aspect. But I guess this is a viable feature, though I would stop adding more possible configuration in order to keep this easy-to-use (yeah I´m looking at you webpack). :-)
