### ISSUE TITLE
v1.1.9 introduced breaking changes

### ISSUE THREAD

**Issue by Scarysize** [txchen/light-server#22]
The release v1.1.9 introduced breaking changes (https://github.com/txchen/light-server/commit/eee02a4a17124ce05d83e3e4e4b4641935fa7243), so the version should be bumped to `2.0.0` (major). Otherwise a simple `npm install` will get you a version which is incompatible with your current `.lightrc` file.

**Comment by txchen** [comment]
thanks! I will try to handle it.

**Comment by txchen** [comment]
Fixed by publish 1.1.10 and 2.0.0.

**Comment by Scarysize** [comment]
👍 Thank you!
