### ISSUE TITLE
bind address

### ISSUE THREAD

**Issue by aves84** [txchen/light-server#23]
Hello!

I tried to use with Docker, and couldn't connect. As far as I found out, the reason is that server is bound to the address 127.0.0.1.

I have fix this by specify `-b 0.0.0.0` or `-b "`. In this case the connection is set.

But I think it's worth to set the default address to `null`.

**Comment by txchen** [comment]
@aves84 IMHO, bind to 127.0.0.1/localhost is widely used in most of the server softwares (like express, koa), as default value. Since we already have the -b switch, seems it is not blocking you:)

So I am closing this issue.

**Comment by aves84** [comment]
It is not correct, experss by default as node http server used exactly undefined/null and binds to 0.0.0.0, netstat output for example: `tcp6       0      0 :::3000                 :::*                    LISTEN      20854/node`

**Comment by txchen** [comment]
Thanks for the info, I will check it.

**Comment by txchen** [comment]
Updated in 2.0.2.
Thanks @aves84 again!
