### ISSUE TITLE
SPA support

### ISSUE THREAD

**Issue by vkrepkiy** [txchen/light-server#25]
May you add support for SPA applications with single entry point? Now if you route to http://localhost/router/path it returns static (404) and proxy is no help. I've quickly [forked](https://github.com/vkrepkiy/light-server/commit/) light-server, but it'd be nice to see an option like { "spa" : "entryPoint.html"} in the main distr.

**Comment by txchen** [comment]
good suggestion, I will take a loot to see if it is easy to implement. Thanks!

**Comment by txchen** [comment]
@vkrepkiy implemented in 2.2.0, please help to have a try. Let me know if there are issues.
Thanks again for the suggestion!
