### ISSUE TITLE
Feature request: optionally execute watch trigger at startup

### ISSUE THREAD

**Issue by lwchkg** [txchen/light-server#29]
As title. I suggest using the switch `-W` (compared to `-w`) to state a watch that will be triggered unconditionally at startup, so we can build the site by starting light-server.

**Comment by txchen** [comment]
@lwchkg Thanks for the suggestion and sorry for being so late to respond.

`-W` can work, however I think the .lightrc should also be supported. So how about this:

If the command (2nd part of the expression) starts with `!`, like `!npm run build`, then it would be executed when light-server is started. In this way, we don't need to introduce a new field in config file.

Let me know what do you think, thanks a lot!

**Comment by txchen** [comment]
Close this since no response.
