### ISSUE TITLE
Allow disabling live-reloading

### ISSUE THREAD

**Issue by gkalpak** [txchen/light-server#35]
More specifically, I want to be able to prevent the HTML content from being altered while serving. 

Most of the time I love watching+live-reloading, but in some specific cases I want to prevent the served content from being altered:

https://github.com/txchen/light-server/blob/0b76abaf386b438433eb7475ae6352e4fc6c4fad/index.js#L56

Sounds like a straight forward enough feature. Happy to submit a pull request if you are fine adding it.

##
More on the usecase:
I am trying to use `light-server` to serve an app using [Angular][1]'s [service-worker][2] module. In a nutshell, the ServiceWorker will compute the sha1 hash of the received files and check if it matches what it expects based on its configuration and/or caches.

By modifying the HTML content (to append the live-reload script), it changes the sha1 hash of the file, messing up with my ServiceWorker 😞 

[1]: https://angular.io/
[2]: https://angular.io/guide/service-worker-intro

**Comment by txchen** [comment]
Thanks for the issue. I'd like to understand your problem better:

If we don't inject the html, we cannot get browser auto reload. Does that mean you will manually reload the page? If that's the case, what value can light-server bring?

**Comment by gkalpak** [comment]
Yes, in these specific cases (where I don't want the HTML tampered with), I will have to manually reload.
`light-server` will be used for easily serving a directory, on a specific port, with 404 fallback index.

(Right now, I use `light-server` most of the time, but have to switch to a different server (which doesn't support `historyindex` :cry:) for testing the ServiceWorker. It would be nice if I could always use `light-server :grin:)

I understand this is not a very common requirement and you probably want to keep `light-server` small and focused, but it seemed like an simple change (i.e. removing/disabling a feature, not adding one), so I thought I'd ask :smiley:

**Comment by txchen** [comment]
Got it. If you could send a PR, we can continue the discussion from there, does that sound good?
