### ISSUE TITLE
Problem with truncated watch value

### ISSUE THREAD

**Issue by isZZ** [txchen/light-server#37]
Hi and thanks for the very useful project,

when I use the -watch option from the example copied below in my package.json, it seems to result in the watch option value that is passed to the LightServer server function in index.js being truncated.

I'm expecting this  'src/**/*.html # npm run build:js #' but seem to be getting this '\'src/**/*.html', resulting in the files not being watched. I can use an external config to get around this.

This could be a stupid mistake on my behalf, but I can't see what it might be.

Thanks Ben

P.S. I'm using windows 8 with npm 3.10.10

 

logged options from light-server/index.js
`{ port: 9090,
  interval: 500,
  delay: 0,
  bind: undefined,
  proxypaths: [ '/' ],
  watchexps: [ '\'src/**/*.html', '\'src/**/*.css' ],
  serve: '.',
  noReload: false }`

package.json

`{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "npm run build:js && npm run build:css",
    "build:js": "browserify -t [riotify --ext html] -d src/index.js -p [minifyify --compressPath . --map index.js.map --output build/index.js.map] -o build/index.js",
    "build:css": "cp src/main.css build/main.css",
    "dev": "light-server -s . -p 9090 -w 'src/**/*.html # npm run build:js #' -w 'src/**/*.css # npm run build:css # reloadcss'"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "lite-server": "^2.3.0"
  },
  "dependencies": {
    "browserify": "^16.2.0",
    "minifyify": "^7.3.5",
    "mocha": "^5.1.0",
    "riot-compiler": "^3.4.0",
    "riotify": "^2.0.0"
  }
}`

**Comment by isZZ** [comment]
@txchen It seems this is a npm and windows problem with nested single quotes. An escaped version with double quotes or the quotes removed seems to fix the problem e.g.

-w \"src/**/*.html # npm run build:js #\"
-w src/**/*.html # npm run build:js #

More info here
https://www.npmjs.com/package/cross-env

Although it's not your issue it may be be worth adding a line to the README.

Thanks again

**Comment by txchen** [comment]
I evaluated the possible fix for single quotes on windows, I thought it will not be a perfect idea because it cannot deal with some edge cases.
So instead, I will update the doc, to ask users to use double quotes.

**Comment by txchen** [comment]
Thanks again! I am closing this.
