### ISSUE TITLE
[Question/Request] Any way to enable brotli and gzip compression?

### ISSUE THREAD

**Issue by br0wnie** [txchen/light-server#39]
Is there a way to use a [brotli module](https://www.npmjs.com/package/iltorb) and a [gzip module](https://www.npmjs.com/package/compression) with light-server? Light-server is amazing, and I was hoping for a way to add brotli and gzip compression for testing, but have no idea how to do it.

So if there isn't a way to already do that with light-server, I guess this is a request? Either way, thanks for the awesome module!

**Comment by txchen** [comment]
@br0wnie light-server is mainly used in development time, not designed for prod environment, so I'd like to know the reason why you think compression is important. Could you please elaborate?

**Comment by br0wnie** [comment]
It probably isn't important, I'm pretty new to all of this and mostly wanted to see the effects of compression on my files. I don't have a production environment, just my localhost setup right now. I figured I'd ask just in case!

**Comment by txchen** [comment]
I see, thanks for the information:)

In that case, I suggest you setup a prod-like environment for that kind of verification. Pick a mature http server like nginx or caddy, I personally don't suggest doing content compression in js layer.
