### ISSUE TITLE
ERR Connection refused

### ISSUE THREAD

**Issue by Alex-Intection** [txchen/light-server#40]
Hello,

did you experience any connection refused errors in the last days, due to CORS / cross origin headers?
Without them, all browsers stopped working with websockets a few days ago.

Dont't know if it's just my system, or i misconfigured something. But its not working anymore.
Just wanted to inform you in case you experience similar issues.

Thanks a lot.

Alexander

**Comment by txchen** [comment]
@Alex-Intection no, I haven't updated this for a while.
Please help to share your version, your npm lock file, your config, or detailed repro step, so that we can take a deeper look.

**Comment by txchen** [comment]
Close this as it is not active.
