### ISSUE TITLE
Redirecting extension-less paths to trailing `/`

### ISSUE THREAD

**Issue by gkalpak** [txchen/light-server#41]
By calling `serveStatic` [without specifying a `redirect` option][1], `light-server` "inherits" the default `serveStatic` behavior for [redirect][2], which is to _"redirect to trailing '/' when the pathname is a dir"_.

By "is a dir", they mean "does not contain an extension (e.g. `.html`).

##
This was breaking some tests for me, where I was comparing against the browser URL against a know value and they deferred (by a trailing `/`). (Not a huge deal, but still annoying.)

##
In today's apps - and especially for SPAs - it is very common for URLs to not have an extension and still not point to directories. 

I think it would be a good idea to use `redirect: false`, either by default or at least when `historyindex` is specified.

WDYT, @txchen?

[1]: https://github.com/txchen/light-server/blob/b432a7b1b40e8b209cf8421b058e55ba283af0fa/index.js#L74
[2]: https://github.com/expressjs/serve-static#redirect

**Comment by txchen** [comment]
@gkalpak Thanks for the issue, though I don't think I fully understand your point.
Would you please help to provide an example and the desired behavior? That might help.

**Comment by gkalpak** [comment]
Sorry for not being clear.  What I meant is:
When I navigate to `http://localhost:4000/foo`, I get redirected to `http://localhost:4000/foo/` (notice the trailing slash). That's what I want to avoid.

**Comment by txchen** [comment]
Got it, I will take a look.

**Comment by txchen** [comment]
I am actually not seeing redirect, when SPA mode is used (historyindex). But I agree with you @gkalpak  it should be redirect: false.

**Comment by txchen** [comment]
https://github.com/txchen/light-server/commit/1504422a35421c8f5343cbc87b5c78e132a31cf6 Please verify if this change fixes your issue or not, thanks!

**Comment by gkalpak** [comment]
Thx for making the change, @txchen ❤️

I was trying it out and I realized that I actually only get the extra `/` when I use `--historyindex /` (which I am using as a shorthard for `--historyindex /index.html` - and it works fine btw :grin:).
I tried applying `{ redirect: false }` [here][1] as well and - while it avoids the extra `/` - `--histroyindex /` stops redirecting to `/index.html`.

Not sure why it behaves like this, but it's fine by me (since I can avoid adding the extra `/` by using `--historindex /index.html` instead of `--historyindex /`) 👍 

[1]: https://github.com/txchen/light-server/blob/b432a7b1b40e8b209cf8421b058e55ba283af0fa/index.js#L74
