### ISSUE TITLE
Feature request: List directory contents

### ISSUE THREAD

**Issue by gkalpak** [txchen/light-server#42]
It would be if `light-server` could (either by default or with an option) serve directory listings.
As mentioned in expressjs/serve-static#67, `serveStatic` (which is what `light-server` already uses) can be [combined with `serveIndex`][1] to achieve that. 

[1]: https://github.com/expressjs/serve-index#serve-directory-indexes-with-vanilla-nodejs-http-server

**Comment by txchen** [comment]
Thanks for the suggestion! Added in https://github.com/txchen/light-server/commit/3f475fba3f4558fcabc3bfbd4ed09c44ba36e2f4

**Comment by gkalpak** [comment]
:tada: :heart:
