### ISSUE TITLE
Proxy path issue

### ISSUE THREAD

**Issue by zeg-io** [txchen/light-server#43]
I have a UI (react) and an API (node).  The node server is on port 3100 and responds to queries to `/v1/find/SERVERNAME/SERIAL` where servername and serial are variables.

The react API calls `/api/v1/find/SERVERNAME/SERIAL`

When I hit any of the APIs `/api/auth` or the above I see a 404 listed and the traffic keeps the `/api` folder structure.  Is there a way to have `/api/` forward traffic to the root of the server without keeping the `/api/` part of the path?

light-server-config.json
```json
{
  "serve": "build",
  "port": 4000,
  "bind": "localhost",
  "watchexps": [
    "**.html # npm run build",
    "**.js # npm run build",
    "*.css # # reloadcss"
  ],
  "interval": 500,
  "delay": 0,
  "proxy": "http://localhost:3100",
  "proxypaths": [ "/api" ],
  "noReload": false,
  "quiet": false,
  "open": true,
  "http2": false,
  "historyindex": "/index.html"
}
```

**Comment by txchen** [comment]
Just curious, how do you plan to run your project in prod environment? 
How do you plan to make the proxy logic to do the redirection to trim the `/api`?

light-server is only designed for dev-time, so I assume you need to do the same logic with some other tools.
