### ISSUE TITLE
Disable cache?

### ISSUE THREAD

**Issue by devinrhode2** [txchen/light-server#44]
I'm just wondering how I could ensure the caching is disabled?

**Comment by txchen** [comment]
You can disable cache in chrome dev tool, does that work?

**Comment by devinrhode2** [comment]
Some people reviewing my work are not technical :(

**Comment by devinrhode2** [comment]
I have light server being broadcasted from a spare laptop via localtunnel

**Comment by txchen** [comment]
I see. I assume the cache you mentioned is made by serve-static, which is usually keyed by etag, if the file content changed, the client should download the new content in theory. 

May I know why the cache is blocking your work?

**Comment by devinrhode2** [comment]
Ok, issues were definitely caused from my inexperience with a new mercurial
tool

Updating files seems to break the cache

-Devin <http://devinrhode2.github.io>
<http://devinrhode2.github.io/>
