### ISSUE TITLE
PATCH/PUT requests always return HTTP status 405

### ISSUE THREAD

**Issue by simonedavico** [txchen/light-server#45]
With the latest version of light-server (2.6.0) `PUT` and `PATCH` requests (I did not have the chance to try `POST` requests) always return a `405` status code.

The same does not occur with the previous release, 2.5.1.

In case it may be useful, I am proxying requests to `/api` to an external URL, like so:

`yarn light-server -s build -p 3000 --historyindex '/index.html' -x http://localhost:8080 --proxypath '/api'  --no-reload`

**Comment by papasmurf17** [comment]
I've the same issue

**Comment by don-p** [comment]
+1

**Comment by txchen** [comment]
Thanks for the issue. Fixed in light-server@2.6.1
