### ISSUE TITLE
usage of --proxy param in cli breaks static file resolution

### ISSUE THREAD

**Issue by pwrinc** [txchen/light-server#46]
Hi, with the latest version of `light-server` (`2.6.1`) I'm facing an issue when using the `--proxy` parameter:

Assuming the following file structure:
```
/node_modules
/public
  |- index.html
package.json
```

Starting `light-server` with `light-server -s public/ --proxy https://github.com` and calling `localhost:4000/index.html` does NOT return `index.html` from local folder `public`. Instead it logs a `502` code and proxies the request to `github.com`.

When starting `light-server` without proxy `light-server -s public/` everything works fine and `localhost:4000/index.html` returns file from local folder `public` like expected.

It seems like the proxy options breaks the lookup for static files. Using Version `2.6.0` of `light-server` does not have this error.

**Comment by hrbu** [comment]
+1

**Comment by txchen** [comment]
Thanks for reporting! My last change should be related, I will take a look!

**Comment by jtrs** [comment]
+1

**Comment by txchen** [comment]
Made a fix in 2.6.2, could you please help to verify? Thanks!

**Comment by pwrinc** [comment]
Seems to work now. Thanks!

**Comment by martindzejky** [comment]
This is still broken in `v2.6.4` 😞
