### ISSUE TITLE
MIME types incorrect for livereload.js

### ISSUE THREAD

**Issue by fidian** [txchen/light-server#49]
When getting the JavaScript to kick off the live reload of the page, the response does not have a `Content-Type: application/javascript`. This is causing a problem when I'm trying to use the live reload functionality with Chrome, which has strict MIME type checking enabled. I believe the fix to this would be to just change the line that serves the JavaScript. This worked for me.

    // old
    res.writeHead(200)

    // new
    res.writeHead(200, { 'Content-Type': 'application/javascript' });

**Comment by txchen** [comment]
Thanks! @fidian  I will try to fix this.

**Comment by fidian** [comment]
Thanks!
