### ISSUE TITLE
changeOrigin true

### ISSUE THREAD

**Issue by joelcollinsdc** [txchen/light-server#5]
I'm totally new to this, apologies if I'm off base.

I'm trying to use light-server to proxy to something thats non-local and needs a host header to work.

<code>
light-server -x http://fake.example.com
</code>

However, the responses i'm getting appear as though the web server isn't receiving the host header fake.example.com (just a request on the IP address)

This doesn't work unless I hack proxy.js to add this:

<code>
  _this.proxy = httpProxy.createProxyServer({ changeOrigin: true })
</code>

Should this be an option?  Set by default?

**Comment by txchen** [comment]
@joelcollinsdc thanks for reporting this! It looks like a bug, I will look into this soon.

**Comment by txchen** [comment]
@joelcollinsdc I changed to use changeOrigin: true, and published 1.1.1
Thanks again!
