### ISSUE TITLE
Config option to block certain files

### ISSUE THREAD

**Issue by adueppen** [txchen/light-server#51]
I've been using light-server for a website that has a service worker, and so far my best option has been to comment out the registration in my JS whenever I need to test. This isn't ideal, so it would be nice to have a config option to not load certain files, something along the lines of this:
```
"blockexps": [
    "dist/service-worker.js"
]
```

**Comment by txchen** [comment]
@adueppen I took a look at the packages I am using to serve static, `serve-static` and `send`. They have no options to enable this feature, so this will be not trivial to implement.
PR is welcome if you figure out an easier way to this.
