### ISSUE TITLE
Remote access

### ISSUE THREAD

**Issue by illycz** [txchen/light-server#55]
Is it possible access address from other device like within Browser Sync?

Thanks

**Comment by txchen** [comment]
It is now default bind to 0.0.0.0, so remote device can access the service.

**Comment by illycz** [comment]
Thanks for reply. I'm on same wifi, run my server and I can't access it from my phone on 0.0.0.0 or 0.0.0.0:port-number

Any suggestion?

**Comment by txchen** [comment]
On your phone you need to use your computer's ip to access, and you need to make sure no firewall is blocking the traffic on your computer.

**Comment by illycz** [comment]
Hm computers's ip with or withoup port not working.
`The requested URL / was not found on this server.` :(

**Comment by illycz** [comment]
When I shut down MAMP, Safari can't  access to server...

**Comment by txchen** [comment]
I think this is not a light-server issue. You can try using other http server, for example, `python3 -m http.server` to test as well.

**Comment by illycz** [comment]
But when I'm using browser-sync on other project, everything working as expected...

**Comment by illycz** [comment]
python server also working 🤷‍♂️

**Comment by illycz** [comment]
Sorry my fault, this is not my project and there was config file within different binding option. Now everything is working.

Thanks for your time!
