### ISSUE TITLE
Redirect when using servePrefix

### ISSUE THREAD

**Issue by G100g** [txchen/light-server#56]
Hi, 
 first thank you for your package. Very useful.

I'm using `servePrefix` option to serve my dev environment under the subpath, like in production.

Could be very useful to create an automatic redirect from `http://localhost:4000` to `http://localhost:4000/subpath/`

Let me know if I can submit a PR for that.

Best

**Comment by txchen** [comment]
@G100g What if we print `http://localhost:4000/subpath/` on the console output, and you can click the link to open it?

**Comment by G100g** [comment]
Hi @txchen , sorry for delay.

For sure this will help, but actually our console output contain also webpack logs, so the information about the server url is lost during the development.

A redirect will help.

Something like this
```js
if (_this.options.servePrefix) {
      app.use('/', function (req, res, next) {
        res.writeHead(301, {
          'Location': _this.options.servePrefix
        });
        res.end()
      })
    }
```

Let me know if is feasible for you and if i can sent you a PR.
Best
