### ISSUE TITLE
redirect option for serveStatic

### ISSUE THREAD

**Issue by G100g** [txchen/light-server#58]
Hi, 
 we'd like to enable redirect from `/my/path` to `/my/path/`

I see that the `redirect`option on `serverStatic` is set to false.

Do you think this could be ad option we can set from the config file?

Thank yout

**Comment by alexpeattie** [comment]
Yes, it would be wonderful if this was configurable ☺️

**Comment by txchen** [comment]
Thanks @G100g for the suggestion! Added in 2.7.0, currently only supporting it through rc file.
