### ISSUE TITLE
Add a negate example for WatchExpression

### ISSUE THREAD

**Issue by waveiro** [txchen/light-server#62]
I just wanted to start saying thanks for this amazing project.

Ligth-server uses Gaze to handle the watch on the files specified on the -w/--watch parameter.

And Gaze does offer a negate pattern which can be useful on various situations. For example what happened to me was that I needed to watch all the files except one that was generated by a build command. However this causes a endless loop, because the build changed the file which triggered it again...

So maybe adding one such as this, could be useful: 

> light-server -s ./public -w \"./**, !./logs/** # npm run build && echo wow!\" -p 4300

I understand maybe the above is not the best example, but I believe one case for negate could be useful.

**Comment by txchen** [comment]
Thanks @waveiro ! This is useful, I added to the readme.
