### ISSUE TITLE
not auto reload

### ISSUE THREAD

**Issue by G33kNoob** [txchen/light-server#65]
im trying use light-server put index.html + style.css 
after i edit css the page not autoreload

**Comment by txchen** [comment]
Do you mind sharing your project files or a repro step?

**Comment by xinxilas** [comment]
Me too..

Simple as that
desktop folder:
-index.html
-javascripts.js

Run 
light-server -s . -p 80 -o -b 127.0.0.1

html
```
<!DOCTYPE html>
<html>
<body>
    <h1>Script tester!</h1>
    <script type="text/javascript" src="javascript.js"></script>
</body>
</html>
```
javascript
```
const fn = n => n

let start = Date.now()

let num = 2
//for (let i = 0; i < 1000; i++) { num += fn(i) - fn(i) + fn(i) - fn(i) + fn(i) + fn(i)}
for (let i = 0; i < 1000; i++) { num += i - i + i - i + i + i}

document.body.innerHTML += `<br>${(Date.now() - start)}`
```

I want to reload when ichange javascript.js
But it doesn't work on .html neither

**Comment by txchen** [comment]
@xinxilas you need to use `-w, --watchexp <watch expression>` to specify the files to watch.
