### ISSUE TITLE
RC file?

### ISSUE THREAD

**Issue by joelcollinsdc** [txchen/light-server#7]
We are using this (amazing) tool on a shared development environment (ugh) where people have to remember to specify the correct IP and port combination for it to work.  I was wondering, do you think it woudl be a good idea to support some kind of ~/.light-server.rc file configuration which would be used as defaults for the user so they don't have to specify certain flags over and over?  This also helps us keep our IP addresses out of package.json...

**Comment by txchen** [comment]
@joelcollinsdc That's a nice idea, I will try to implement this. Thanks!

**Comment by txchen** [comment]
@joelcollinsdc Implemented in 1.1.5, please help to have a try, thanks!
