### ISSUE TITLE
Add support for 2KB keys or configurable ones

### ISSUE THREAD

**Issue by tnarik** [txchen/light-server#71]
Hi,

Would it be possible replacing the 1KB keys by 2KB keys to better support some Linux distribution recommendations related to security?
Alternatively, please offer configuration options to support easy replacement of the default self signed certificate.

**Comment by txchen** [comment]
Thanks for the suggestion. To confirm, are you referring to `localhost.key/crt`?

**Comment by tnarik** [comment]
Yes. Exactly those files. We had to overwrite them in the module itself to
allow usage on a Linux box, but that is a bit untidy.

**Comment by txchen** [comment]
updated the cert to 2KB, in 2.9.0
