### ISSUE TITLE
Silent / less verbose mode

### ISSUE THREAD

**Issue by eliot-akira** [txchen/light-server#8]
Would it be possible to add an option for less or no console messages?

Thank you for the versatile tool, I just reduced a folder full of gulp tasks to a few lines of npm script and am quite happy about it.

**Comment by txchen** [comment]
@eliot-akira Thanks for the suggestion, I will take a look.

**Comment by eliot-akira** [comment]
I imagine it's a matter of wrapping all `console.log()` to be conditional. If it's too tedious, please feel free to disregard the idea. The messages are actually helpful to see exactly what's happening - I followed along by reading the code, and I love how concise it is. Anyway, my thought was that it might be nice to have a quiet mode, maybe with a single message: `light-server is listening at http://localhost:4000`

**Comment by txchen** [comment]
@eliot-akira currently it would print http request, file changes, and command executed.
Which parts do you think should be optional? 

I want to know more about your motivation: typically when you run the server, other than the light-server's output, what do you expect to see on the console?

**Comment by eliot-akira** [comment]
What I imagine is a silent mode with a single line from light-server with the host and port. So, no console output for each http request, file changes, or command executed. Then, on file change, the executed commands will display their own messages.

```
$ npm run server

light-server is listening at http://localhost:4000

Bundled JS to dist/app.js (on file change, message from executed command)
```

**Comment by txchen** [comment]
1.1.3 published to npm, please verify if it works for you.
Thanks for the PR, really appreciate it!

**Comment by eliot-akira** [comment]
That's excellent, I confirmed that it works perfectly.

Thanks so much for such a useful well-written tool. It's great that the codebase is so compact and approachable, I learned a lot from studying how it works. I'm moving all my projects to use light-server in the build process, it does everything I need with minimum setup. Bravo!
